name: Get coverage

on:
  pull_request:

  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: read
      id-token: write

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Install package
        run: |
          pip install -e .[dev]

      - name: Run test suite
        run: |
          set -o pipefail
          pytest --cov-report xml --cov=twsfw

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./coverage.xml
