name: Run test suite

on:
  pull_request:

  push:
    branches:
      - main
      - dev

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Install package
        run: |
          pip install -e .[dev]

      - name: Run test suite
        run: |
          pytest
